services:
  postgres:
    image: postgres:latest
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
  api:
    image: node:18-alpine
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - ./:/app
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/curty?schema=public
    command: sh -c "npm run prisma:dev && npm run dev"
volumes:
  db-data: